strip unneeded dylibs from linking
In JAN 2026 Homebrew apparently make some changes to suite-sparse to
fix crosslinking between gcc's libgomp and the libomp package.

This patch fixes errors like:

```
RuntimeError: dynamic loading error (libDomTools.dylib)
dlsym(RTLD_DEFAULT, __tgt_omp_free): symbol not found
```